export let users = [
    {id:1,name:"Joe",profile:"https://images.unsplash.com/flagged/photo-1566127992631-137a642a90f4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&w=1000&q=80"},
    {id:2,name:"Sam",profile:"https://images.all-free-download.com/images/graphiclarge/vervet_monkey_female_266097.jpg"},
    {id:3,name:"Tom",profile:"https://api.time.com/wp-content/uploads/2014/09/macaca_nigra_self-portrait_rotated_and_cropped.jpg?quality=85&w=666&h=628&crop=1"},
    {id:4,name:"Jerry",profile:"https://www.rd.com/wp-content/uploads/2020/12/GettyImages-78777891-scaled.jpg"},
    {id:5,name:"John",profile:"https://upload.wikimedia.org/wikipedia/commons/5/5a/Proboscis_monkey_%28Nasalis_larvatus%29_female_Labuk_Bay.jpg"},
]

export let chat=[
    {msg:"Hi",id:1,time:new Date()},
    {msg:"Hi",id:2,time:new Date()},
    {msg:"What's up",id:1,time:new Date()},
    {msg:"What's happening",id:1,time:new Date()},
    {msg:"Nothing much",id:2,time:new Date()},
    {msg:"Fog happening",id:2,time:new Date()},
    {msg:"tell me",id:1,time:new Date()},
    {msg:"what ?",id:2,time:new Date()},
    {msg:"Something",id:1,time:new Date()},
    {msg:"I have nothing,I have nothing",id:2,time:new Date()},
    {msg:"You will have something",id:1,time:new Date()},
    {msg:"Yeah I have a block button",id:2,time:new Date()},
    {msg:"Oh no! I pressed it :)",id:2,time:new Date()},
     {msg:"Hi",id:1,time:new Date()},
    {msg:"Hi",id:2,time:new Date()},
    {msg:"What's up",id:1,time:new Date()},
    {msg:"What's happening",id:1,time:new Date()},
    {msg:"Nothing much",id:2,time:new Date()},
    {msg:"Fog happening",id:2,time:new Date()},
    {msg:"tell me",id:1,time:new Date()},
    {msg:"what ?",id:2,time:new Date()},
    {msg:"Something",id:1,time:new Date()},
    {msg:"I have nothing,I have nothing",id:2,time:new Date()},
    {msg:"You will have something",id:1,time:new Date()},
    {msg:"Yeah I have a block button",id:2,time:new Date()},
    {msg:"Oh no! I pressed it :)",id:2,time:new Date()},
]

